# Generated by Django 3.1.4 on 2021-01-30 13:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2021, 1, 30, 13, 13, 1, 866263, tzinfo=utc))),
            ],
        ),
    ]
