# Generated by Django 3.1.4 on 2021-01-31 07:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20210130_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 31, 7, 23, 37, 987931, tzinfo=utc)),
        ),
    ]
