# Generated by Django 3.1.4 on 2021-01-31 10:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_auto_20210131_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 31, 10, 42, 34, 321515, tzinfo=utc)),
        ),
    ]
